# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2024.09.1
_src_path: gh:astrojuanlu/copier-pylib
author_email: juan_luis_cano@mckinsey.com
author_name: Juan Luis Cano Rodríguez
github_org: astrojuanlu
package_name: kedro_catalog
project_name: kedro-catalog
short_description: Next-generation DataCatalog for Kedro
